// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;


#[derive(serde::Serialize, Queryable, Insertable, Identifiable)]
pub struct Booking {
    pub id: String,
    pub date: String,
    pub amount_cents: i32,
    pub details: String,
    pub comment: Option<String>,
    pub currency: String,
    pub receipt_url: Option<String>,
    pub tax_code: Option<String>,
    pub debit_account: String,
    pub credit_account: String,
    pub txn_id: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(serde::Serialize, Queryable, Insertable, Identifiable)]
#[primary_key(path)]
pub struct Document {
    pub path: String,
    pub state: String,
    pub docid: String,
    pub date: String,
    pub sum: i32,
    pub tags: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(serde::Serialize, Queryable, Insertable, Identifiable)]
#[primary_key(invoice_id)]
pub struct Invoice {
    pub invoice_id: String,
    pub date: String,
    pub amount_cents: i32,
    pub currency: String,
    pub tax_code: String,
    pub order_id: Option<String>,
    pub payment_method: String,
    pub line_items: String,
    pub sales_account: String,
    pub customer_account: String,
    pub customer_company: Option<String>,
    pub customer_name: String,
    pub customer_address_1: String,
    pub customer_address_2: Option<String>,
    pub customer_zip: String,
    pub customer_city: String,
    pub customer_state: Option<String>,
    pub customer_country: String,
    pub vat_included: String,
    pub replaces_id: Option<String>,
    pub replaced_by_id: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

